### ISSUE TITLE
Allow device binding by id

### ISSUE THREAD

**Issue by freakshock88** [Forceu/barcodebuddy-docker#10]
Hi!

I'm currently using barcode buddy via docker on a ubuntu host, with a physical scanner.
It all worked perfectly, until I rebooted by server and the device address changed from  /dev/input/event4 to /dev/input/event3. This means every time I reboot my server I run the change of having to setup my container again because the address has changed.
Is it possible to bind to the address using something like a device id? 

If I run this command: 
`ls -l /dev/input/by-id/ `
I get the following response:
`lrwxrwxrwx 1 root root 9 janv. 21 19:10 usb-Netum._HIDKB_18502-event-kbd -> ../event3`

Thanks in advance :)

**Comment by Forceu** [comment]
Thank you for your request. I didn't think of that, as my barcode scanner has always the same device number. In that case you would need to setup a udev rule.

With a quick Google search I found this website, which might be helpful: http://weng-blog.com/2017/05/udev-rule/

When I have the time I will write some documentation or even an automatic script for the udev rule.

**Comment by freakshock88** [comment]
Any update on this? I looked into it but I'm not sure how to setup this myself.. Thanks.

**Comment by Forceu** [comment]
Thanks for the follow up! At the moment I don't have a lot of time unfortunately, the earliest I could implement this would be next month. I will set a reminder though ;)

**Comment by dkruzic** [comment]
Can you explain how the udev rule would help here? It can only add another symlink not fix the id of the input device so it doesn't give us anything we don't already get in `/dev/input/by-id/`

**Comment by freakshock88** [comment]
Just wondering if you had any time to look into this issue? ;)

**Comment by freakshock88** [comment]
Still having this issue, wondering if you have some time to look into it? :)

**Comment by Forceu** [comment]
Reddit user [Ape3000](https://www.reddit.com/user/Ape3000) found a way to bind devices from the docker host by ID, would that work for you?

> Not sure if this useful, but this is how I got my USB scanner working:

`docker run -dv bbconfig:/config -e ATTACH_BARCODESCANNER=true -p 4343:80 --device /dev/input/by-id/usb-1a86_5455-event-kbd:/dev/input/event0 f0rc3/barcodebuddy-docker:latest`

**Comment by freakshock88** [comment]
Awesome, that seems to work fine :) Thanks for the reply !

**Comment by Forceu** [comment]
Added in https://github.com/Forceu/barcodebuddy-documentation/commit/cb18e797c21e115baa4573ebfa8cb59552b14124
