### ISSUE TITLE
Offer option to set UID and GID for the user running barecodebuddy in the Docker container

### ISSUE THREAD

**Issue by Forceu** [Forceu/barcodebuddy-docker#11]
Originally posted here by @wechsler42: https://github.com/Forceu/barcodebuddy/issues/109

Hi there,
first of all thank you very much for sharing barecode buddy with us! I use it in a Docker environment together with the Android app.
I would like to suggest to offer a possibility to set the UID and the GID for the user used to run barecode buddy in the docker container.
I work with this docker-compose file, user 1002 is a designated docker user on my docker host:

version: '2.1'
services:
barcodebuddy-docker:
volumes:
- 'path_to_my_directory_on_docker_host:/config'
ports:
- '8082:80'
- '9443:443'
image: 'f0rc3/barcodebuddy-docker:v1.5.1.0'
user: "1002:100"
restart: unless-stopped

When I use a user other than root to run barecode buddy in the container than I receive this error: "s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied".

**Comment by Forceu** [comment]
@wechsler42 thank you for the issue. As I am personally only using rootless podman I never had that problem, but I will look into it.

**Comment by Forceu** [comment]
@wechsler42 Does it work if you add the parameters -e PUID=1002 and -e PGID=100 to the docker command or if you are using compose

```
environment:
  - PUID=1002
  - PGID=100
```

**Comment by wechsler42** [comment]
Thanks Forceau,
I used docker-compose with the following docker-compose.yml which worked flawlessly.


version: '2.1'
services:
barcodebuddy-docker:
volumes:
    - 'path_to_my_directory_on_docker_host:/config'
    ports:
      - '8082:80'
      - '9443:443'
    image: 'f0rc3/barcodebuddy-docker:v1.5.1.0'
    environment:
         - PUID=1002
         - PGID=100
    restart: unless-stopped

**Comment by Forceu** [comment]
Great to hear! I will add it to the documentation :)
