### ISSUE TITLE
Websocket issues

### ISSUE THREAD

**Issue by llewy** [Forceu/barcodebuddy-docker#2]
Thanks for the docker-image! But I still have websocket-issues, even while I'm not using any SSL.
![image](https://user-images.githubusercontent.com/525767/77160507-bb23f500-6aa7-11ea-8e29-471079e5e529.png)
![image](https://user-images.githubusercontent.com/525767/77160405-8ca61a00-6aa7-11ea-9a36-758e2d015162.png)

What am I doing wrong, can't stand it for not figuring it out :-)

**Comment by Forceu** [comment]
Thanks for the report! I will push an update either today or tomorrow that uses Server-Sent Events instead of websockets for external communication, this would then not require any configuration at all.

**Comment by llewy** [comment]
Thanks a lot!

**Comment by Forceu** [comment]
Apparently the php-socket package was not included in the previous build. It is included now, also I changed over to SSE instead of websockets, now everything should be working out of the box :)
