### ISSUE TITLE
ODROID Ubuntu 22.04 Docker

### ISSUE THREAD

**Issue by magtimmermans** [Forceu/barcodebuddy-docker#24]
Hi,

When I install the docker image using docker compose. I got an error in the web inteface:

`Installed: curl
Installed: date
Installed: sqlite3
Installed: json
Installed: sockets
Installed: redis
Installed: mbstring
Not installed: gettext (required)`

I tried to install gettext but no better result still:
**Not installed: gettext (required)**

this is the docker-compose file:

`
  barcodebuddy:
    image: f0rc3/barcodebuddy-docker:arm64v8-v1.8.1.5
    container_name: barcodebuddy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./volumes/barcodebody/config:/config
    ports:
      - 9284:80
      - 444:443
    restart: unless-stopped
`

**Comment by Forceu** [comment]
Thanks for the report, there was indeed a problem with the arm64 Dockerfile. I updated the image, does it work now?

**Comment by magtimmermans** [comment]
Yes, its working.
