### ISSUE TITLE
Update manifest file

### ISSUE THREAD

**Issue by taeganw** [Forceu/barcodebuddy-docker#25]
Good morning. I can only pull the latest tag from docker hub. Can you update the manifest file so I can pull for a different architecture?

Ex.) 

$ docker pull f0rc3/barcodebuddy-docker:arm64v8-latest
Pulling from f0rc3/barcodebuddy-docker no matching manifest for linux/arm64/v8 in the manifest list entries

Thank you!

**Comment by NossieUK** [comment]
plz?

Pulling barcodebuddy (f0rc3/barcodebuddy-docker:arm64v8-latest)...
arm64v8-latest: Pulling from f0rc3/barcodebuddy-docker
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by Forceu** [comment]
I am currently rewriting the Dockerfile to remove dependencies, once it's finished in a couple of days, the problem should be solved as well.

**Comment by NossieUK** [comment]
thank you kindly, was worried it might have been getting abandoned

**Comment by Forceu** [comment]
So I finished updating the file, it was a lot more work than expected. Please try the image `f0rc3/barcodebuddy-docker:latest-dev` (which is now a multi-arch image) and let me know if it is working

**Comment by taeganw** [comment]
This is working for me. Thank you for fixing the problem!
