### ISSUE TITLE
Docker run doesn't create new container.

### ISSUE THREAD

**Issue by jyGwx4RwQJ** [Forceu/barcodebuddy-docker#3]
I have grocy running in docker (docker-compose) but I can't get barcodebuddy-docker to run.  The output of my logs is:

`standard_init_linux.go:211: exec user process caused "exec format error"`

I have a feeling this is an architecture issue.  I'm running on a raspberry pi 3B+, my architecture is armv7, although Alpine should support this.  Any ideas?

**Comment by Forceu** [comment]
Have you used ´docker pull f0rc3/barcodebuddy-docker:arm32v7-latest´? That would be the correct tag for your architecture

**Comment by jyGwx4RwQJ** [comment]
That totally solved it, thank you for the quick reply.

**Comment by Forceu** [comment]
Great to hear! I will probably make a note in the readme about that
