### ISSUE TITLE
Add option to allow insecure ssl certificates

### ISSUE THREAD

**Issue by spyder94** [Forceu/barcodebuddy-docker#4]
I have the Grocy add-on running in Hass.io and I'm trying to connect it to barcodebuddy running in Docker.  I can access the Grocy API using https://192.168.0.12:9192/api/ but when I put that value into the barcodebuddy setup screen along with the correct API key, I just get "Unable to connect to API: Could not connect to server."

When I run this, I get an appropriate response, I know the url and api key I'm entering are correct: 
`curl -k -H "GROCY-API-KEY:MY_API_KEY" -X GET "https://192.168.0.12:9192/api/system/info" -H "accept: application/json"`

Any help would be appreciated.

**Comment by spyder94** [comment]
It appears the problem is due to my Grocy setup using SSL.  When I change it to not use SSL, I'm able to get barcodebuddy to connect to it.  This is not ideal since disabling SSL causes certain features of Grocy to not function.  My guess here is that barcodebuddy is trying to valid the SSL certificate, which won't work when specifying an IP address for the url.  I can't give it the duckdns.org hostname for the url because my router won't do NAT hairpinning.

Maybe an option on the setup page to ignore SSL would be handy.

**Comment by Forceu** [comment]
Thanks for your input! I will add an option to ignore invalid SSL certificates

**Comment by Forceu** [comment]
Added in 05a282b1346089ab8d06c8f990764a8ffa71938c

You can pull the latest dev-image with `docker pull f0rc3/barcodebuddy-docker:latest-dev` and then change `CURL_ALLOW_INSECURE_SSL_CA` to `true` in `/app/bbuddy/incl/config.php`

Later today I will probably add an docker environment variable, so it does not have to be changed manually

**Comment by Forceu** [comment]
In the current latest-dev build, you can now pass environment variables to ignore SSL errors:
Pass `-e IGNORE_SSL_CA=true` to ignore self-signed certificates and `-e IGNORE_SSL_HOST=true` if the host does not match the certificate.
