### ISSUE TITLE
Consume same quantity as Purchased

### ISSUE THREAD

**Issue by T-h-o-m-a-s** [Forceu/barcodebuddy-docker#5]
When setting a quantity (by scanning the quantity barcode) it works perfectly when purchasing. But it would be great if that was also (optionally) applied to consuming.

Example: Parent product Egg. Child products are Egg boxes of various sizes. Adding number of eggs is easy. But I also consume eggs by box/carton, not egg by egg. 

The more "normal" usecase with for example sixpack of cola - the bottles have their own barcode and the pack has its own too. 

The best option would be if default quantities could be entered in the UI and also chosen if to apply by purchase and/or consume.

**Comment by Forceu** [comment]
Sorry for the late reply.

This issue is related to the core app, not docker. I opened a ticket there: https://github.com/Forceu/barcodebuddy/issues/39

**Comment by Forceu** [comment]
Added in https://github.com/Forceu/barcodebuddy/commit/d47ef11867967f9b08ab9010491cb75ea8c1541e
