### ISSUE TITLE
Clean install failed using latest image

### ISSUE THREAD

**Issue by GerardRibas** [Forceu/barcodebuddy-docker#6]
Hi @Forceu!

First of all many thanks for your Barcode Buddy tool!

I tried to update to the latest image this afternoon but it seems that something is not right, I've just tried to do a clean install like:

`docker run -d -v bbconfig:/config -p 8099:80 -p 4430:443 f0rc3/barcodebuddy-docker:latest`

but I've got:
```
2020/04/14 15:19:17 [error] 344#344: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Delight\Db\Throwable\Error: could not find driver in /app/bbuddy/incl/authentication/composer/vendor/delight-im/db/src/ErrorHandler.php:87
Stack trace:
#0 /app/bbuddy/incl/authentication/composer/vendor/delight-im/db/src/PdoDatabase.php(476): Delight\Db\ErrorHandler::rethrow(Object(PDOException))
#1 /app/bbuddy/incl/authentication/composer/vendor/delight-im/db/src/PdoDatabase.php(498): Delight\Db\PdoDatabase->ensureConnected()
#2 /app/bbuddy/incl/authentication/composer/vendor/delight-im/db/src/PdoDatabase.php(568): Delight\Db\PdoDatabase->normalizeConnection()
#3 /app/bbuddy/incl/authentication/composer/vendor/delight-im/db/src/PdoDatabase.php(125): Delight\Db\PdoDatabase->selectInternal(Object(Closure), 'SELECT roles_ma...', Array)
#4 /app/bbuddy/incl/authentication/composer/vendor/delight-im/auth/src/Administration.php(282): Delight\Db\PdoDatabase->selectValue('SELECT roles_ma...', Array)
#5 /app/bbuddy/incl/authentication/authentication.inc.php(34): Deli" while reading response header from upstream, client: 192.168.1.157, server: _, request: "GET /login.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.1.2:8099"
```

Is there anything new that I have to install in the container?

Thanks!

**Comment by Forceu** [comment]
Thanks a lot for your feedback! I forgot to add the new dependencies to the stable build. It should be                working now with the current image, can you confirm that?

**Comment by GerardRibas** [comment]
> Thanks a lot for your feedback! I forgot to add the new dependencies to the stable build. It should be working now with the current image, can you confirm that?

Hey @Forceu seems working absolutely fine! 

Many thanks for that!

**Comment by Forceu** [comment]
Great to hear, thank you! :)
