### ISSUE TITLE
No support for i386

### ISSUE THREAD

**Issue by Forceu** [Forceu/barcodebuddy-docker#8]

**Comment by bluckholl** [comment]
@Forceu I want to thank you so much! what a pro! 🥇 
I emailed you just a few days ago and you managed to add this support quickly,
Having also previous i386 docker images such 1.5.1.0 was really helpful as I didn't upgrade grocy yet,
Everything is running now smoothly, with a physical scanner! wow!
I realize amazed by the software, documentation, and support, keep up the great job :)
Asaf

**Comment by Forceu** [comment]
Hey, I actually send you a reply, maybe it went to spam.
Great to hear it is working now! In the long term it would be probably cheaper to use a raspberry pi, as it consumes only a fraction of the electricity your computer.
Also thank you so much for your donation, I really appreciate it!! Merry Christmas :)
