### ISSUE TITLE
Doesn't work with linuxserver.io grocy Image

### ISSUE THREAD

**Issue by darkcloud784** [Forceu/barcodebuddy-docker#9]
Unfortunately the newest versions of BBB don't seem to work with the current latest version from linuxserver.io. Are there any work arounds for this other than pinning to something old?

**Comment by Forceu** [comment]
I just tried it and seems to work fine. What exactly is the error message? And have you updated both images to the latest version?

**Comment by darkcloud784** [comment]
Nevermind, the issue was my own idiocy. Closing.
